services:
  - type: web
    name: fact-check-agent
    env: python
    plan: free

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt

    startCommand: streamlit run streamlit_app.py --server.port $PORT --server.address 0.0.0.0

    healthCheckPath: /_stcore/health

    envVars:
      - key: GROQ_API_KEY
        sync: false

      - key: OPENAI_API_KEY
        sync: false